replicaCount: 3
## if replicaCount < 2, set podDisruptionBudget.enabled to false, to avoid eviction issues
## Otherwise, set to true
podDisruptionBudget:
  enabled: true

wordpress:
  existingSecret: wparctic-wordpress
  persistence:
    existingClaim: wparctic-wordpress-0
  resources:
    requests:
      cpu: "250m"
      memory: 500Mi
    limits:
      cpu: "500m"
      memory: 1Gi

mariadb:
  existingSecret: wparctic-mariadb
  persistence:
    existingClaim: wparctic-wordpress-mariadbd-0
  resources:
    requests:
      cpu: "250m"
      memory: 500Mi
    limits:
      cpu: "500m"
      memory: 1Gi

ingress:
  host: &hostname wp-dev.test.dataone.org

adminIngress:
  host: *hostname
