replicaCount: 3
## if replicaCount < 2, set podDisruptionBudget.enabled to false, to avoid eviction issues
## Otherwise, set to true
podDisruptionBudget:
  enabled: true

wordpress:
  image:
    ## Starting version was "6.8.2-php8.2-apache"
    ##
    tag: "7-php8.5-apache"
    pullPolicy: Always
  existingSecret: wparctic-wordpress
  persistence:
    existingClaim: wparctic-wordpress-0
  resources:
    requests:
      cpu: "250m"
      memory: 500Mi
    limits:
      cpu: "500m"
      memory: 1Gi

mariadb:
  image:
    ## Starting version was "11.4"
    ##
    tag: "12.2"
  existingSecret: wparctic-mariadb
  persistence:
    existingClaim: wparctic-wordpress-mariadbd-0
    subPath: data
  resources:
    requests:
      cpu: "250m"
      memory: 500Mi
    limits:
      cpu: "500m"
      memory: 1Gi

ingress:
  ## @param ingress.host The domain name of the main public WordPress site (e.g. "arcticdata.io")
  ##
  host: wp-dev.test.dataone.org

adminIngress:
  ## @param adminIngress.host The domain name of the WordPress Admin site (eg: "wp-admin.arcticdata.io")
  ## IMPORTANT:
  ## If you are running only ONE WP pod (replicaCount: 1) this must be the same as ingress.host
  ## If you are running 2 OR MORE WP pods (replicaCount: 2 or more), use a DIFFERENT domain to avoid
  ## issues when editing Themes in Preview Mode
  ##
  host: wp-dev-admin.test.dataone.org
