{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "apache-datasvc.fullname" . }}
  labels:
    {{- include "apache-datasvc.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace -}}
            -{{ .Release.Name }}-cors-headers@kubernetescrd"
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http: &httpPathsAlias
        paths:
          - path: /icons/
            pathType: Prefix
            backend:
              service:
                name: {{ include "apache-datasvc.fullname" $ }}
                port:
                  name: http
          {{- range $p := $.Values.routes }}
          - path: {{ $p.ingressPath }}
            pathType: {{ $p.ingressPathType }}
            backend:
              service:
                name: {{ include "apache-datasvc.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- if .Values.ingress.tlsWwwPrefix }}
    - host: www.{{ .Values.ingress.hostname }}
      http: *httpPathsAlias
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range $tls := .Values.ingress.tls }}
    - hosts:
        {{- range $h := $tls.hosts }}
        - {{ $h }}
        {{- end }}
        {{- if $.Values.ingress.tlsWwwPrefix }}
        {{- range $h := $tls.hosts }}
        - www.{{ $h }}
        {{- end }}
        {{- end }}
      secretName: {{ $tls.secretName }}
    {{- end }}
  {{- end }}
{{- end }}
