{{- if .Values.adminIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wparctic.wordpressName" . }}-admin
  labels:
    {{- include "wparctic.labels" . | nindent 4 }}
    app.kubernetes.io/component: wordpress
  annotations:
    {{- toYaml .Values.adminIngress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.adminIngress.className }}
  rules:
    - host: {{ .Values.adminIngress.host }}
      http:
        paths:
          - path: {{ .Values.adminIngress.path }}
            pathType: {{ .Values.adminIngress.pathType }}
            backend:
              service:
                name: {{ include "wparctic.wordpressName" . }}
                port:
                  name: http
          {{- range .Values.adminIngress.extraPaths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "wparctic.wordpressName" $ }}
                port:
                  name: http
          {{- end }}
  tls:
    - hosts:
        - {{ .Values.adminIngress.host }}
      secretName: {{ .Values.adminIngress.tlsSecretName }}
{{- end }}
