apiVersion: v1
kind: Service
metadata:
  name: {{ include "wparctic.mariadbName" . }}-headless
  labels:
    {{- include "wparctic.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
