##
## This file contains "redirect" middleware definitions for Traefik.
##
## IMPORTANT: ADD THE NAMES OF ANY NEW MIDDLEWARES TO helm/templates/middleware-chain.yaml, OR THEY
## WON'T BE LOADED!
##
{{- range .Values.adminIngress.rewriteRules }}
---
##
## Pull any custom redirects from .Values.ingress.rewriteRules
##
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $.Release.Name }}-{{ .name }}-admin
  namespace: {{ $.Release.Namespace }}
spec:
  redirectRegex:
    regex: {{ .regex | quote }}
    replacement: {{ .replacement | quote }}
    permanent: {{ default "false" .permanent }}
{{- end }}
