##
## This file contains Traefik "headers" Middleware definitions for Security-related headers
##
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $.Release.Name }}-security-headers-public
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    customResponseHeaders:
      ## disallow showing in someone else's iframe:
      X-Frame-Options: SAMEORIGIN

    ## strict-transport-security: max-age=31536000; includeSubDomains:
    forceSTSHeader: true
    stsSeconds: 31536000
    stsIncludeSubdomains: true
