apiVersion: v1
kind: Service
metadata:
  name: {{ include "wparctic.wordpressName" . }}
  labels:
    {{- include "wparctic.labels" . | nindent 4 }}
    app.kubernetes.io/component: wordpress
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: wordpress
  ports:
    - name: http
      port: 80
      targetPort: http
  sessionAffinity: ClientIP
